import type { Metadata } from "next";
import './globals.css'
import { QueryProviders } from "./provider/QueryClientProvider";
import { dehydrate, QueryClient } from "@tanstack/react-query";
import { getCurrentUser } from "./lib/auth-server";
// import { USER_QK } from "./types/auth";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const qc = new QueryClient()
  // const user = await getCurrentUser()
  // qc.setQueryData(["user"], user)
  return (
    <html lang="en" suppressHydrationWarning>

      <body className="flex min-h-screen bg-gray-50 dark:bg-gray-900 content-transition">
        <QueryProviders >
          {children}
        </QueryProviders>
      </body>
    </html>
  );
}
