import type { Metadata } from "next";
import './globals.css'
import { QueryProviders } from "./provider/QueryClientProvider";
import { getCurrentUser } from "./service/auth-server";
import { QueryClient } from "@tanstack/react-query";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // const queryClient = new QueryClient();
  // const user = await getCurrentUser();
  // console.log(user);
  // if (user) {
  //   queryClient.setQueryData(['user', "user"], user)
  // } else {
  //   queryClient.setQueryData(["user", 'user'], null);
  // }

  // const dehydratedState = dehydrate(queryClient);
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="flex min-h-screen bg-gray-50 dark:bg-gray-900 content-transition">
        <QueryProviders >
          {children}
        </QueryProviders>
      </body>
    </html>
  );
}
