import type { Metadata } from "next";
import Sidbar from "../_Components/Sidbar";
import { Providers } from "../provider/ThemeProvider";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
            <div className="flex  w-full min-h-screen bg-gray-50 dark:bg-gray-900 content-transition">
                <Providers>
                    <Sidbar />
                    {children}
                </Providers>
            </div>
    );
}
