import type { Metadata } from "next";
import Sidbar from "../_Components/Sidbar";
import { Providers } from "../provider/ThemeProvider";
// import { QueryClient } from "@tanstack/react-query";
// import { getCurrentUser } from "../lib/auth-server";
// import { USER_QK } from "../types/auth";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <div className="flex  w-full min-h-screen bg-gray-50 dark:bg-gray-900 content-transition">
            <Providers >
                <Sidbar />
                {children}
            </Providers>
        </div>
    );
}
