# Kubernetes Secret for DEV environment (SOPS-encrypted placeholders)
# Namespace is chosen at apply time (`kubectl -n dev apply -f -`).
apiVersion: v1
kind: Secret
metadata:
  name: veggieshop-app-secrets
  labels:
    app.kubernetes.io/name: veggie-shop
    app.kubernetes.io/part-of: veggie-shop
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: ENC[AES256_GCM,data:1m3n6dZl42Q=,iv:Q0y8Sg8k+z3yZ8m0pIu3hQ==,tag:s7pQb2s9F0o=,type:str]
  SPRING_DATASOURCE_PASSWORD: ENC[AES256_GCM,data:W8b1KqkqCY0=,iv:8YxJpO7Kq8q3b5oZb2RzjQ==,tag:6Hh5l0g4QmE=,type:str]
  JWT_SECRET:                 ENC[AES256_GCM,data:V2VnZ2llU2hvcC1EZXYtSldULVNlY3JldA==,iv:3kL8qQ1bGkz1U5cBfP4qvA==,tag:g9G3mP1qT7c=,type:str]
  MINIO_ACCESS_KEY:           ENC[AES256_GCM,data:bWluaW8=,iv:nW3b+fM9m4J7vU2x+1q4WA==,tag:GZq0XoYJ2nI=,type:str]
  MINIO_SECRET_KEY:           ENC[AES256_GCM,data:bWluaW8xMjM=,iv:Q2aVh0s7Tq8nM2pLr9i0GQ==,tag:J6QXh3Q7p2o=,type:str]
sops:
  mac: ENC[AES256_GCM,data:x/placeholder-mac-x,iv:iviviviviv,tag:tagtagtag,type:str]
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1exampleexampleexampleexampleexampleexampleexampleexample
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRlZC1ibG9iLXBsYWNlaG9sZGVy
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-20T14:40:25Z"
  encrypted_regex: '^(data|stringData)$'
  version: 3.7.3
