# Kubernetes Secret for STAGING environment (SOPS-encrypted placeholders)
# Namespace is chosen at apply time (`kubectl -n staging apply -f -`).
apiVersion: v1
kind: Secret
metadata:
  name: veggieshop-app-secrets
  labels:
    app.kubernetes.io/name: veggie-shop
    app.kubernetes.io/part-of: veggie-shop
type: Opaque
stringData:
  # Optional: full JDBC URL consumed by values-prod.yaml (.env.valueFrom.secretKeyRef: jdbcUrl)
  jdbcUrl:                     ENC[AES256_GCM,data:amRiYzpwZ3NxbC8vZGItcGxhY2Vob2xkZXIv,...,iv:...,tag:...,type:str]
  SPRING_DATASOURCE_USERNAME:  ENC[AES256_GCM,data:c3RhZ2luZw==,iv:6V2m8cU9q+q5GvJ3qGmFVg==,tag:PQm3n3gT9r0=,type:str]
  SPRING_DATASOURCE_PASSWORD:  ENC[AES256_GCM,data:c3RhZ2luZy1wYXNz,iv:4nVn3qF9f6s0pLz2tNfJfQ==,tag:ZlY0h7YkQ2A=,type:str]
  JWT_SECRET:                  ENC[AES256_GCM,data:V2VnZ2llU2hvcC1TdGFnLUpXVC1TZWNyZXQ=,iv:8dQ7kP3cF2b1S0oHqN1t3A==,tag:q0M2xG9wH5E=,type:str]
  MINIO_ACCESS_KEY:            ENC[AES256_GCM,data:c3RhZ2luaW8=,iv:Z0p1R2m3N8q0vX1bC7y2gQ==,tag:V5v7b6N0QyM=,type:str]
  MINIO_SECRET_KEY:            ENC[AES256_GCM,data:c3RhZ2luaW8xMjM=,iv:D8f1yJ3lQ6r8nT2bK9p0eA==,tag:H1r4w2Q9L6c=,type:str]
sops:
  mac: ENC[AES256_GCM,data:x/placeholder-mac-x,iv:iviviviviv,tag:tagtagtag,type:str]
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1exampleexampleexampleexampleexampleexampleexampleexample
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRlZC1ibG9iLXBsYWNlaG9sZGVy
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-20T14:40:25Z"
  encrypted_regex: '^(data|stringData)$'
  version: 3.7.3
