name: Security & Code Scanning

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "30 2 * * 0" # Weekly scan on Sundays at 02:30 UTC
  workflow_dispatch:

permissions:
  contents: read
  security-events: write   # Required for CodeQL to upload results
  actions: read
  pull-requests: read

concurrency:
  group: security-${{ github.ref }}
  cancel-in-progress: true

jobs:
  codeql:
    name: CodeQL (Java)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java
          # Queries can be tuned later if needed

      - name: Set up JDK 21 (Temurin) with Maven cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Build for CodeQL database
        run: mvn -s ci/maven-settings.xml -B -ntp -DskipTests clean compile

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:java"

  dependency-review:
    # This runs only on pull requests and fails on new vulnerable dependencies
    if: ${{ github.event_name == 'pull_request' }}
    name: Dependency Review (PR)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          # Fail on critical or high vulnerabilities; adjust as desired
          fail-on-severity: high
