server:
  port: 8080

spring:
  security:
    user:
      name: ${ADMIN_USER:admin}
      password: ${ADMIN_PASS:admin123}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/vegetable_shop}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:secret}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

app:
  jwt:
    secret: ${JWT_SECRET:5WTQ5zL14Ue0v5U6Hphqr5Zp6byKePG0A2hYXnN2OMpQyY4tdgWJ8xuvq1UHKADyB5m8fWlb6T6B6SGk9OKlOKg==}
    expiration-ms: ${JWT_EXPIRATION:86400000}
