#######################################################################
# VeggieShop — Spring Boot Application Configuration (Base)
# - Keep ONLY environment-agnostic defaults here.
# - Secrets/URLs/timeouts should be overridden per environment.
#######################################################################

spring:
  application:
    name: veggie-shop

  profiles:
    # Default to "local" unless SPRING_PROFILES_ACTIVE is provided externally
    active: ${SPRING_PROFILES_ACTIVE:local}

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    default-property-inclusion: non_null
    time-zone: UTC

  mvc:
    async:
      request-timeout: 30s
    problemdetails:
      enabled: true  # RFC7807 standardized error responses

  servlet:
    multipart:
      enabled: true
      max-file-size: ${UPLOAD_MAX_FILE_SIZE:20MB}
      max-request-size: ${UPLOAD_MAX_REQUEST_SIZE:40MB}
      file-size-threshold: 2MB

  # JPA/Flyway shared defaults — schema managed by Flyway
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        jdbc.time_zone: UTC
        connection.provider_disables_autocommit: true
        generate_statistics: ${HIBERNATE_STATS:false}

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    connect-retries: 3

  # Cache defaults (choose redis/caffeine/none per env)
  cache:
    type: ${CACHE_TYPE:redis}
    redis:
      time-to-live: 600000           # 10 minutes
      cache-null-values: false
      key-prefix: ${CACHE_PREFIX:veggie:}
      use-key-prefix: true

  mail:
    default-encoding: UTF-8
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail.smtp.auth: ${MAIL_SMTP_AUTH:false}
      mail.smtp.starttls.enable: ${MAIL_SMTP_STARTTLS:false}
    test-connection: ${MAIL_TEST_CONNECTION:false}

server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful
  forward-headers-strategy: native
  compression:
    enabled: true
    min-response-size: 2KB
    mime-types: application/json,application/xml,text/html,text/plain,text/css,application/javascript
  tomcat:
    threads:
      min-spare: ${TOMCAT_MIN_THREADS:10}
      max: ${TOMCAT_MAX_THREADS:200}
    max-swallow-size: 2MB
    max-http-form-post-size: 5MB
  error:
    include-message: never
    include-binding-errors: never
    whitelabel:
      enabled: false

# Observability (Actuator, Micrometer, Tracing)
management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics,prometheus,threaddump,loggers,env,configprops,httpexchanges
  endpoint:
    health:
      probes:
        enabled: true
      show-details: ${MANAGEMENT_HEALTH_DETAILS:when_authorized}
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      region: ${REGION:local}
      env: ${ENV:local}
  observations:
    key-values:
      app: ${spring.application.name}
  tracing:
    enabled: ${TRACING_ENABLED:true}
    sampling:
      probability: ${TRACING_SAMPLING:0.1}
    baggage:
      remote-fields: X-Trace-Id,X-Request-Id
      correlation:
        fields: X-Trace-Id

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    org.springframework: ${LOG_LEVEL_SPRING:INFO}
    org.hibernate.SQL: ${LOG_LEVEL_HIBERNATE_SQL:WARN}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOG_LEVEL_HIBERNATE_BIND:WARN}
    com.veggieshop: ${LOG_LEVEL_APP:INFO}
  file:
    name: ${LOG_FILE:} # e.g., /var/log/veggie/app.log (empty = console)

springdoc:
  api-docs:
    enabled: ${SPRINGDOC_ENABLED:true}
    path: /v3/api-docs
  swagger-ui:
    enabled: ${SWAGGER_UI_ENABLED:true}
    path: /swagger-ui
    operationsSorter: alpha
    tagsSorter: alpha

app:
  cors:
    enabled: ${CORS_ENABLED:true}
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
    allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,PATCH,DELETE,OPTIONS}
    allowed-headers: ${CORS_ALLOWED_HEADERS:*}
    exposed-headers: ${CORS_EXPOSED_HEADERS:X-Trace-Id,Content-Disposition}
    allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}
    max-age: 3600

  security:
    jwt:
      issuer: ${JWT_ISSUER:veggieshop}
      access-token-ttl: ${JWT_ACCESS_TTL:15m}
      refresh-token-ttl: ${JWT_REFRESH_TTL:7d}
      # Keys are environment-specific; do NOT commit real values.
      secret: ${JWT_SECRET:dev-please-change-me}
      public-key: ${JWT_PUBLIC_KEY:}
      private-key: ${JWT_PRIVATE_KEY:}
      clock-skew: 5s

  ratelimit:
    enabled: ${RATE_LIMIT_ENABLED:true}
    window: ${RATE_LIMIT_WINDOW:1m}
    requests: ${RATE_LIMIT_REQUESTS:100}

  tracing:
    inbound-headers: X-Trace-Id,X-Request-Id,X-Correlation-Id,traceparent
    response-header: X-Trace-Id

  async:
    core-pool-size: ${ASYNC_CORE:8}
    max-pool-size: ${ASYNC_MAX:32}
    queue-capacity: ${ASYNC_QUEUE:2000}
    keep-alive: ${ASYNC_KEEPALIVE:60s}
    allow-core-thread-timeout: ${ASYNC_ALLOW_TIMEOUT:false}
    shutdown-await: ${ASYNC_AWAIT:30s}
    thread-name-prefix: ${ASYNC_PREFIX:async-}
    scheduler-pool-size: ${SCHED_CORE:4}
    scheduler-thread-name-prefix: ${SCHED_PREFIX:sched-}
    propagate-security-context: ${ASYNC_PROPAGATE_SECURITY:true}
    metrics-name: ${ASYNC_METRICS_NAME:veggieshop.executor}
