server:
  port: 8080

spring:
  security:
    user:
      name: ${ADMIN_USER:admin}
      password: ${ADMIN_PASS:admin123}
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/vegetable_shop}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:secret}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET:MySuperSecretKey}
  expiration: ${JWT_EXPIRATION:86400000}
